from __future__ import annotations

import argparse
import json
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = ROOT / "decision_log.json"
DEFAULT_OUTPUT = ROOT / "docs" / "decision_log.md"


@dataclass
class DecisionEntry:
    section: str
    subsection: str | None
    path: str
    payload: dict[str, Any]


def _title_from_key(key: str) -> str:
    return key.replace("_", " ").strip().title()


def _find_best_title(entry: dict[str, Any]) -> str:
    for candidate in ("decision", "title", "limitation", "description", "name", "category"):
        value = entry.get(candidate)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return "(no summary available)"


def _normalize_scalar(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _flatten_value(value: Any) -> str:
    if isinstance(value, (str, int, float, bool)) or value is None:
        return _normalize_scalar(value)
    return json.dumps(value, ensure_ascii=False)


def _collect_entries(data: dict[str, Any]) -> list[DecisionEntry]:
    entries: list[DecisionEntry] = []

    def walk(node: Any, path: list[str], top_section: str | None, subsection: str | None) -> None:
        if isinstance(node, dict):
            if isinstance(node.get("id"), str) or isinstance(node.get("adr_id"), str):
                section_name = top_section or "Uncategorized"
                entries.append(
                    DecisionEntry(
                        section=section_name,
                        subsection=subsection,
                        path="/".join(path),
                        payload=node,
                    )
                )
            for key, child in node.items():
                next_section = top_section
                next_subsection = subsection
                if len(path) == 0:
                    next_section = _title_from_key(key)
                    next_subsection = None
                elif len(path) == 1 and key in {"log", "entries", "decisions"}:
                    next_subsection = _title_from_key(path[0])
                walk(child, [*path, key], next_section, next_subsection)
        elif isinstance(node, list):
            for index, child in enumerate(node):
                walk(child, [*path, str(index)], top_section, subsection)

    walk(data, [], None, None)
    return entries


def _group_entries(entries: Iterable[DecisionEntry]) -> OrderedDict[str, OrderedDict[str | None, list[DecisionEntry]]]:
    grouped: OrderedDict[str, OrderedDict[str | None, list[DecisionEntry]]] = OrderedDict()
    for entry in entries:
        grouped.setdefault(entry.section, OrderedDict()).setdefault(entry.subsection, []).append(entry)
    return grouped


def render_markdown(data: dict[str, Any], source_path: Path) -> str:
    project = data.get("project", {}) if isinstance(data.get("project"), dict) else {}
    project_name = project.get("name") or "Decision Log"
    source_last_updated = project.get("last_updated")

    entries = _collect_entries(data)
    grouped = _group_entries(entries)

    lines: list[str] = []
    lines.append(f"# {project_name} — Decision Log (Generated)")
    lines.append("")
    lines.append(
        "This document is auto-generated from `decision_log.json`. "
        "Do not edit this file directly; update the JSON source instead."
    )
    lines.append("")
    lines.append(f"- Source: `{source_path.as_posix()}`")
    if isinstance(source_last_updated, str) and source_last_updated.strip():
        lines.append(f"- Generated from source version: {source_last_updated.strip()}")
    lines.append(f"- Total decision entries: {len(entries)}")
    lines.append("")

    for section, subsection_map in grouped.items():
        lines.append(f"## {section}")
        lines.append("")
        for subsection, section_entries in subsection_map.items():
            if subsection:
                lines.append(f"### {subsection}")
                lines.append("")
            for item in section_entries:
                raw_id = item.payload.get("id")
                if not isinstance(raw_id, str):
                    raw_id = item.payload.get("adr_id")
                decision_id = _flatten_value(raw_id)
                title = _find_best_title(item.payload)
                lines.append(f"#### {decision_id} — {title}")
                lines.append("")
                preferred_order = [
                    "id",
                    "adr_id",
                    "date",
                    "category",
                    "title",
                    "decision",
                    "limitation",
                    "description",
                    "rationale",
                    "outcome",
                    "stakeholder",
                    "estimated_impact",
                    "estimatedImpact",
                    "risk",
                    "impact",
                    "implementation",
                    "tradeoff",
                    "next_decision_needed",
                    "note",
                ]
                emitted = set()

                for key in preferred_order:
                    if key in item.payload:
                        lines.append(f"- **{key}**: {_flatten_value(item.payload[key])}")
                        emitted.add(key)

                for key in item.payload.keys():
                    if key not in emitted:
                        lines.append(f"- **{key}**: {_flatten_value(item.payload[key])}")

                lines.append(f"- **source_path**: `{item.path}`")
                lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def generate(input_path: Path, output_path: Path) -> None:
    data = json.loads(input_path.read_text(encoding="utf-8"))
    markdown = render_markdown(data, input_path.relative_to(ROOT))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Markdown from decision_log.json")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT, help="Path to decision JSON file")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Path to generated Markdown file")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_path = args.input.resolve()
    output_path = args.output.resolve()
    generate(input_path, output_path)
    print(f"Generated {output_path}")


if __name__ == "__main__":
    main()
